export const modCategoryNames = {
    ammo: 'Ammo',
    barrel: 'Barrel',
    barrelExtension: 'Barrel Ext.',
    bayonet: 'Bayonet',
    bipod: 'Bipod',
    boost: 'Boost',
    custom: 'Custom',
    extra: 'Extra',
    foregrip: 'Foregrip',
    gadget: 'Gadget',
    grip: 'Grip',
    lowerReceiver: 'Lower Receiver',
    magazine: 'Magazine',
    sight: 'Sight',
    slide: 'Slide',
    stock: 'Stock',
    upperReceiver: 'Upper Receiver',
    };